name: jopen
description: JOpen is a Plugin that allows you to open any files in Android, JOpen provides a way to open files by file path.
version: 0.0.2
homepage: https://github.com/AymanYassinn/
repository: https://github.com/AymanYassinn/JOpen

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jucodes.jopen
        pluginClass: JOpenPlugin

